# Generated by Django 5.1.7 on 2025-03-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0002_item_created_at_item_image_item_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Soft Delete'),
        ),
    ]
